version: '3.6'
services:
  load_balancer:
    build:
      context: ./load-balancer
    ports:
     - "443:443"
    environment:
     - KEYCLOAK_FQDN=${KEYCLOAK_FQDN}
     - RESOURCE_FQDN=${RESOURCE_FQDN}
     - CONFORMANCE_SUITE_FQDN=${CONFORMANCE_SUITE_FQDN}
    depends_on:
     - keycloak
     - api_gateway_nginx
     - httpd
    networks:
      default:
        aliases:
         - ${KEYCLOAK_FQDN}
         - ${RESOURCE_FQDN}
         - ${CONFORMANCE_SUITE_FQDN}
  keycloak:
    build:
      context: ./keycloak
      args:
        KEYCLOAK_BASE_IMAGE: ${KEYCLOAK_BASE_IMAGE}
        KEYCLOAK_REALM_IMPORT_FILENAME: ${KEYCLOAK_REALM_IMPORT_FILENAME}
    ports:
     - "8787:8787"
    environment:
     - KEYCLOAK_USER=${KEYCLOAK_USER}
     - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
    volumes:
     - ./https/server.pem:/etc/x509/https/tls.crt
     - ./https/server-key.pem:/etc/x509/https/tls.key
     - ./https/client-ca.pem:/etc/x509/https/client-ca.crt
     - ../bin/keycloak-conformance-test:/opt/jboss/keycloak
    command: "-b 0.0.0.0 -Djboss.socket.binding.port-offset=1000 --debug -Dkeycloak.profile=preview"
  api_gateway_nginx:
    build:
      context: ./api-gateway-nginx
    volumes:
     - ./https/server.pem:/etc/x509/https/tls.crt
     - ./https/server-key.pem:/etc/x509/https/tls.key
     - ./https/client-ca.pem:/etc/x509/https/client-ca.crt
     - ./https/ca.pem:/usr/local/share/ca-certificates/keycloak-fapi-ca.pem
    environment:
     - SERVER_NAME=${RESOURCE_FQDN}
     - INTROSPECTION_ENDPOINT_URL=https://${KEYCLOAK_FQDN}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token/introspect
     # JWT access token veirfication can't pass reuse-authorisation-code case
     # - DISCOVERY_URL=https://${KEYCLOAK_FQDN}/auth/realms/${KEYCLOAK_REALM}/.well-known/openid-configuration
     - CLIENT_SECRET=2ef90464-b0fc-4e06-965d-19ef671a3e22
    depends_on:
     - resource_server
     - keycloak
  resource_server:
    build:
      context: ./resource-server
  client_jwks_server:
    build:
      context: ./client_private_keys
    volumes:
      - ./client_private_keys:/keys
    command: /keys
  test_runner:
    build:
      context: ./test-runner
    environment:
     - AUTOMATE_TESTS=${AUTOMATE_TESTS}
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./fapi-conformance-suite-configs:/json-config
    depends_on:
     - load_balancer
     - keycloak
     - server
  mongodb:
    image: mongo
#    volumes:
#     - mongodata:/data/db
  httpd:
    build:
      context: ${OPENID_GIT_URL}#${OPENID_GIT_TAG}:httpd
    ports:
      - "8443:8443"
    depends_on:
      - server
  server:
    build:
      context: ./conformance-suite
      args:
        OPENID_GIT_URL: ${OPENID_GIT_URL}
        OPENID_GIT_TAG: ${OPENID_GIT_TAG}
    ports:
      - "9999:9999"
    volumes:
      - ${MVN_HOME}:/root/.m2
      - ./report:/conformance-suite/report
      - ./fapi-conformance-suite-configs/:/conformance-suite/.gitlab-ci/fapi-conformance-suite-configs/
    environment:
      - CONFORMANCE_SERVER=https://${CONFORMANCE_SUITE_FQDN}
      - CONFORMANCE_DEV_MODE=1
      - MONGODB_HOST=mongodb
    links:
      - mongodb:mongodb
    depends_on:
      - mongodb
      - keycloak
    logging:
      # limit logs retained on host
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"
#volumes:
#  mongodata: